{application,discovery_server_app,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{discovery_server_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[calc,client,discovery_server,discovery_server_app,
                        mpeer,server,test]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
